### ISSUE TITLE
Fix jest tests

### ISSUE THREAD

**Issue by itechify** [autoinvent/conveyor#114]
Standardizing the repo with the other autoinvent projects (#109) had the side effect of breaking the jest tests. I believe the removal of the babel dependencies is the main culprit. We may need to add back in some of the babel dependencies in order to get them to work again. Another option would be to look at how conveyor-schema has its jest tests setup as they do not have babel as a dependency.

**Comment by ruoyangW-dev** [comment]
PR #33 on conveyor-schema for moving some Jest tests over there.
Conveyor should end up with just FlexibleComponent related tests.

**Comment by itechify** [comment]
Resolved by #159 #160
