### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by itechify** [autoinvent/conveyor#120]
Begin converting files from .js / .jsx to .ts / .tsx

- src
  - delete
    - [x] DeleteDetail.js
  - form
    - [x] Breadcrumbs.js
    - [x] Create.js
    - [x] Input.js 
  - input
    - [x] index.js
    - [x] inputComponent.js 
  - table
    - [x] Field.js
    - [x] Filter.js
    - [x] Footer.js
    - [x] Header.js
    - [x] Sort.js
    - [x] Table.js 
  - utils
    - [x] colorHelper.js
    - [x] fileConverter.js
    - [x] optimizeSelect.js
    - [x] timezoneHelper.js
 - [x] Alerts.js
 - [x] consts.js
 - [x] CreateButton.js
 - [x] DarkModeToggle.js
 - [x] Detail.js
 - [x] DetailLink.js
 - [x] Edit.js
 - [x] Index.js
 - [x] main.js
 - [x] Modal.js
 - [x] NullComponent.js
 - [x] Pagination.js
 - [x] PrintButton.js
 - [x] Search.js
 - [x] Tabs.js
 - [x] Tooltip.js
 - [x] TreeTable.js
 - [x] Utils.js

**Comment by DanielHall977** [comment]
Got NullComponent, DarkModeToggle, CreateButton, DeleteLink, PrintButton and Utils.js converted.
Not that reduplicating the work wouldn't be a snap. They're very small and simple files.

**Comment by DanielHall977** [comment]
the small and simple ones are up:  https://github.com/autoinvent/conveyor/pull/122

**Comment by DanielHall977** [comment]
Working on Detail.js/tsx

**Comment by ruoyangW-dev** [comment]
I will start on the bottom with a branch for TreeTable, Tooltip, and Tabs.

**Comment by ruoyangW-dev** [comment]
Seach and Popover as well.

**Comment by DanielHall977** [comment]
detail.js/tsx is ready for peer-review

**Comment by taroken6** [comment]
Going to start on DeleteDetail and Edit for now.

**Comment by apastel** [comment]
Working on files in `form` directory.

**Comment by taroken6** [comment]
DeleteDetail & Edit PR in #126 
Will work on `Alerts`, `Index`, and `input` directory

**Comment by apastel** [comment]
Created PR for `form` files: #129

**Comment by taroken6** [comment]
Previous conversions merged.
Will work on Table directory

**Comment by apastel** [comment]
Taking on `utils` directory

**Comment by ruoyangW-dev** [comment]
Going to do consts, main, and Pagination.

**Comment by ruoyangW-dev** [comment]
Going to finish up with Search.
