### ISSUE TITLE
Search page design cleanup

### ISSUE THREAD

**Issue by itechify** [autoinvent/conveyor#135]
* Display search box at top of page
* Don't highlight the search term in the results
* Display results as links (hyperlink look)
* Display results as `Model Name: Display Value`
* Change "Search" to magnifying glass or relevant icon

**Comment by liwzhang** [comment]
Some bugs that were fixed
- When user quickly types query and hits "enter," the debounced dropdown shows up after routing to SearchPage
- Application crashes when hitting "enter" with an empty query
- Each character typed in the SearchPage input raised its own alert
