### ISSUE TITLE
Create page does not disable field containing the object that called Create.

### ISSUE THREAD

**Issue by DanielHall977** [autoinvent/conveyor#144]
Disabled Input doesn't seem to be working. Field should be greyed out.

**Comment by itechify** [comment]
It may be related to a change to this line a month ago: https://github.com/autoinvent/conveyor-schema/blob/4295b05fcbe26c27769f679f7e04956fc5e7df89/src/callbackGetters.ts#L288

It may need to be `const { form } = stack[stackIndex]` like it was previous

**Comment by ruoyangW-dev** [comment]
PR in conveyor-schema to fix this issue.

**Comment by davidism** [comment]
Link to PR?

**Comment by ruoyangW-dev** [comment]
https://github.com/autoinvent/conveyor/pull/156
