### ISSUE TITLE
Create separate props for QuickSearch and SearchPage inputs

### ISSUE THREAD

**Issue by liwzhang** [autoinvent/conveyor#146]
Currently the input fields for the QuickSearch and SearchPage components are both mapped to the same `queryText` prop. Separate the behavior of the two by creating a `quickSearchQueryText` prop for QuickSearch, a `searchPageQueryText` prop for SearchPage, and any necessary actions.

**Comment by taroken6** [comment]
All changes on autoinvent-example, Conveyor, and Conveyor-Redux works on my end. Code looks good too.
One minor change I have in mind for Autoinvent-example is remove the unnecessary State props in Search Container. Like how Quick Search has [searchPageQueryText](https://gitlab.moesol.com/myurchyshyna/autoinvent-example/-/blob/add-search-prop/src/containers/SearchContainer.js#L23) and Search Page has [quickSearchQueryText](https://gitlab.moesol.com/myurchyshyna/autoinvent-example/-/blob/add-search-prop/src/containers/SearchContainer.js#L23)
