### ISSUE TITLE
Clearing queryText removes search filters from search page

### ISSUE THREAD

**Issue by liwzhang** [autoinvent/conveyor#149]
Clearing the query of either input fields will remove the filters from the search page. Since the search results persist on the page, it makes sense that the filters would also persist. It looks like `searchPageFilters` is being reset by `SEARCH_QUERY_TEXT_CHANGED` when queryText becomes empty, so this may possibly be more of a conveyor-redux issue.

**Comment by apastel** [comment]
Yep, had to make a small update in conveyor-redux. Closing this issue so I can open it there.

**Comment by apastel** [comment]
Fixed in https://github.com/autoinvent/conveyor-redux/pull/76
