### ISSUE TITLE
Better display value for references

### ISSUE THREAD

**Issue by davidism** [autoinvent/conveyor#18]
Currently we just use the `id` field everywhere a model is displayed. That's fine as the link in the index table, but on the detail page, as links from other models, and in form dropdowns, we want a nicer display. Look for a field called `display_value` first, then `name`, then fall back to `id`.

**Comment by robxbob** [comment]
Easy customizability of `ID` ScalarTypes can be done by using the `Conveyor` provider

```jsx
import {Conveyor, ModelIndex, ScalarTypes, ValueRenderFnProps} from '@autoinvent/conveyor'
// . . .
const CustomIdComponent = (props: ValueRenderFnProps) => {
  // value is the data object for a row of data passed in ModelIndex
  return props.value?.display_value 
  // return props.value?.name
  // return props.value?.some_field_of_the_model
} 
// . . .
<Conveyor typeOptions={{
    [ScalarTypes.ID]: {
      valueRenderFn:  CustomIdComponent
    }    
}}>
  <ModelIndex { . . . } />
</Conveyor>

```

Take note, that if all (or most) models contain a display_value field (or common field like name) you can wrap the top level component with `Conveyor`. And yes, `Conveyor`  can be nested where the closest `Conveyor` settings/options are used.
