### ISSUE TITLE
Logo doesn't display when served from CDN

### ISSUE THREAD

**Issue by davidism** [autoinvent/conveyor#19]
The admin nav bar references an image like `/images/logo.png`. That's fine locally, or when used as a library, but doesn't work when loaded from CDN. If your web app serves a page that loads conveyor-admin from CDN, then `/images/logo.png` is relative to the local server that the page was loaded from, not the CDN server that the script was loaded from.

**Comment by robxbob** [comment]
Can now be obtained from 
```html
<img src="https://somecdn/@autoinvent/conveyor/logo.svg"/>
```
or by import
```jsx
import SomeLogo from '@autoinvent/conveyor/logo.svg'
```
