### ISSUE TITLE
Filters for tables

### ISSUE THREAD

**Issue by robxbob** [autoinvent/conveyor#4]
A filter builder UI that supports the dynamic filter capabilities of Magql. This is part of the index table UI.

* Each filter item is `field` select, `not` checkbox, `op` select, `value` input
* Click `+` to add another filter item. These are and-ed together.
* Groups of filter, click `+` to add another group. These are or-ed together.
* `field` select can be manually entered too, `a.b.c.name` would filter on `model.a_relation.b_relation.c_relation.name`.
* "Reset Filter" and "Reset Sort" buttons.
* Save and restore filters and sorts per model in local storage.

**Comment by davidism** [comment]
A filter builder UI that supports the dynamic filter capabilities of Magql:

* Each filter item is `field` select, `not` checkbox, `op` select, `value` input
* Click `+` to add another filter item. These are and-ed together.
* Groups of filter, click `+` to add another group. These are or-ed together.
* `field` select can be manually entered too, `a.b.c.name` would filter on `model.a_relation.b_relation.c_relation.name`.
