### ISSUE TITLE
detail view redirect checks wrong property

### ISSUE THREAD

**Issue by davidism** [autoinvent/conveyor#46]
If the object doesn't exist, the detail component is supposed to render a react-router `Redirect`. It's checking if `node.result` is null, but that will never be the case, either an empty object is passed, or the actual object (not an object with a `result` key containing the object) is passed. The check should probably be if `node` is null or the empty object.

https://github.com/autoinvent/conveyor/blob/868e1dd9a452308aba5b40e14bed224e3ebfee91/src/Detail.js#L685-L687

This causes an additional problem when the object has a `result` field that is nullable, as the detail component will then think valid objects don't exist and redirect away.

**Comment by CodeBloodedChris** [comment]
Simple change to the logic. I've tested it in the Autoinvent Example and it's redirecting correctly when attempting to access a detail page for a model with no data. 
For example: http://localhost:9000/Book/30 is now redirecting to http://localhost:9000/Book
PR: https://github.com/autoinvent/conveyor/pull/47
