### ISSUE TITLE
feature: model index table setting sort ui

### ISSUE THREAD

**Issue by robxbob** [autoinvent/conveyor#49]
### Objective
ModelIndex comes with a table setting button that opens the ModelIndex Settings UI which is comprised of different tabs.
Make a Sort Setting UI which showcases the current sort  as a list to see the sorting order currently being applied. It should behave identical to how sorting a table header works except that this UI shows the ordering on top of being able to customize the ordering.

### Feature
The Sort Setting UI should have the following features:
- Two sections, a sorted section and a non sorted section.
  - Initially if no sorting is applied, a list of fieldnames is shown in the non sorted section.  
- When clicking on non sorted list item, it changes its sort direction and moves it to the sorted section.
- When clicking on a sorted list item, it changes sort direction accordingly and has the potential to be sorted as none which would move it back down to the non sorted section. 
- the sorted section allows drag and drop functionality 
- A save button at the bottom that says "Apply Sorting" 

### Notes
- Use https://dndkit.com/ for making the sort section drag and droppable
- A sub component of what table header cell is using is the sort wrapper. Utilize that. 
- Use ModelIndexTableHeaderCell as reference on how sort is implemented. 
-  You can retrieve the sort property by doing `const sort = useModelIndexStore(state => state.tableView?.sort)`
- Checkout the `sort.ts` file for sort functions under `ModelIndex>utils`; feel free to add a util function there.

### Getting Started
```bash
git clone https://github.com/autoinvent/conveyor/tree/v2
git checkout v2
pnpm install
git checkout -b "feature/modelindex/table/setting-sort-ui"
```
To run the example story do:
```bash
pnpm storybook:css
```

Goto the `ModelIndex > ModelIndex > Basic Usage`  story to play with the example. 
Click on the settings icon on the top right side of the table to see the settings ui and the filters/sort tabs.

**Comment by kurikurichan** [comment]
Working on this

**Comment by robxbob** [comment]
![Screenshot 2024-07-09 124143](https://github.com/autoinvent/conveyor/assets/49213927/2b218242-95a7-4eec-a7ed-aea27da20524)
