### ISSUE TITLE
CSS issues

### ISSUE THREAD

**Issue by robxbob** [autoinvent/conveyor#7]
### Completed
- [x] - String fields should respect newlines, 
- [x] - Make select and inputs be the same size.
- [x] - Pagination, use ~~react-bootstrap~~ shadcn pagination. 
- [x] - ~~Center~~ Left justify checkbox.
- [x] - Set interior color background of inputs to be darker to better distinguish between an input and display. 
- [x] - Remove margin top from table crud buttons.
- [x] - Select Inputs need consistent border with other inputs
- [x] - Match Theme color in inputs, select option menu border, text color.

### Ignored
- ~~Spacing between Modelname and identifier in the title of the detail page~~
  - Conveyor does not have a detail component since its made up of ModelIndex and ModelForm
- ~~Change create button on index page to be a plus icon for consistency.~~ 
  - Removed as create button is a project dependent link to a create page (projects may not even use this button)

**Comment by davidism** [comment]
* String fields should respect newlines, see CSS [`white-space`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) property
