### ISSUE TITLE
Going back from Create page doesn't work as expected

### ISSUE THREAD

**Issue by itechify** [autoinvent/conveyor#89]
When going to a Create page the last history item on the history stack is REPLACED rather than having a new history item added to the stack (PUSH). This might be implemented this way for the formStack (multiple creates), but it has the unintended side-effect of causing the back button to not behave as expected. Because of how this works, pressing back will cause you to go to the page before the one where Create was clicked.

Investigate why this is being done and what (if anything) could be done to address this.

**Comment by ruoyangW-dev** [comment]
Going to look into this issue.

**Comment by DanielHall977** [comment]
Resolved
