### ISSUE TITLE
Excel-like tables

### ISSUE THREAD

**Issue by robxbob** [autoinvent/conveyor#9]
Make tables more excel like:
- inputs fit to cell
- ~~errors for inputs as tooltip along with red border on cell~~ error row underneath current row
- double click to edit mode
- ~~Persist edits~~ **handled by project using conveyor**

**Comment by davidism** [comment]
* Select which columns are visible
* Drag-and-drop to reorder columns
* Drag to resize columns
* Remember and restore layout per model in local storage

**Comment by robxbob** [comment]
In v2
