### ISSUE TITLE
Add dark mode toggle component

### ISSUE THREAD

**Issue by itechify** [autoinvent/conveyor#98]
Create and export a dark mode toggle component.

Should use dark/light mode icons from [react-icons](https://react-icons.github.io/react-icons/) library (ie. IoMdSunny, IoMdMoon).

There will be a related conveyor-redux pr which adds the dark mode toggle actions and the redux store location which should be referenced in the component.

**Comment by davidism** [comment]
Conveyor-Redux will need corresponding state+action
